newsrec:
  db:
    host: localhost # 修改为你自己的虚拟机IP地址
    port: 3306 # 修改为docker中的MySQL端口
    pw: 123456 # 修改为docker中的MySQL密码
    database: nr_new # 修改为你自己的数据库名
  nacos:
    server-addr: localhost:8848
